[mean_field.qe]
name     = "mf_qe"
prefix   = "pwscf"
outdir   = "qe_output_dir/OUT/"
filetype = "h5"

[dmft_embed]
mean_field   = "mf_qe"
outdir       = "./"
prefix       = "mbpt_downfold"
wannier_file = "wan.h5"
