#
# Quantum Espresso mean-field reader
#

[mean_field.qe]
name     = "mf"                           # name tag for this mean_field instance
prefix   = "pwscf"                        # prefix for the quantum espresso outputs
outdir   = "qe_output_dir/OUT/"           # direcotry where the qe outputs locate
filetype = "h5"                           # input format from QE converter:
                                          # "h5": the data format from pw2coqui.x
                                          # "xml": the old format from pw2bgw.x
nbnd     = 40                             # # of bands for MB Hamiltonian, which cannot exceeds "nbnd"
                                          # in the input nscf calculation.
                                          # Defulat = -1, i.e. "nbnd" from the input nscf calculation.