#
# Fully self-consistent GW on the imaignary axis
#

[mean_field.qe]
name     = "mf_qe"
prefix   = "pwscf"
outdir   = "qe_output_dir/OUT/"
filetype = "h5"

[interaction.thc]
name        = "eri"
mean_field  = "mf_qe"
storage     = "incore"
thresh      = 1e-6
chol_block_size = 8
r_blk       = 20
distr_tol   = 0.4

[gw]
interaction = "eri"
beta      = 2000
lambda    = 1200.0
iaft_prec = "high"
niter     = 12               # number of scf iteration
restart   = false            # whether to restart from an existing checkpoint file
conv_thr  = 1e-6
output    = "scgw"               # prefix for the mbpt checkpoint file
div_treatment = "gygi_extrplt"   # finite-size correction to the q->0 divergence in the GW self-energy.
                                 # The recommended option is "gygi_extrplt" for 3D and "gygi_extrplt_2d" for
                                 # layered materials.
                                 # Availalble options are
                                 #   "ignore_g0": no finite-size correction
                                 #   "gygi": approximate dielectric function at q=0 using the closed q-point
                                 #   "gygi_extrplt": approximate dielectric function at q=0 via extrapolation
                                 #   "gygi_extrplt_2d": approximate dielectric function at q=0 via extrapolation on (b1,b2) plane
[gw.iter_alg]
alg    = "damping"
mixing = 0.7
