[mean_field.qe]
name     = "mf_qe"
prefix   = "pwscf"
outdir   = "qe_output_dir/OUT/"
filetype = "h5"

[interaction.thc]
name        = "eri"
mean_field  = "mf_qe"
storage     = "incore"
thresh      = 1e-6
chol_block_size = 8
r_blk       = 20
distr_tol   = 0.4

[evgw0]
interaction = "eri"
beta      = 2000
lambda    = 1200.0
iaft_prec = "high"
niter     = 1
output    = "g0w0"
div_treatment = "gygi"
qp_type   = "sc"
ac_alg    = "pade"
eta       = 1e-6
Nfit      = 26
