[mean_field.qe]
name     = "mf_qe"
prefix   = "pwscf"
outdir   = "qe_output_dir/OUT/"
filetype = "h5"

[interaction.thc]
name        = "eri"
mean_field  = "mf_qe"
storage     = "incore"
thresh      = 1e-6
chol_block_size = 8
distr_tol   = 0.4

[gw]
interaction = "eri"
beta        = 2000
lambda      = 1200.0
iaft_prec   = "high"
niter       = 1
restart     = false
output      = "mbpt_downfold"
div_treatment = "gygi"

[downfold_2e]
input_type    = "coqui"                     # input G^k_ij(tau) type: "mf" or "coqui".
                                            # if "mf": create/overwirte a new/existing coqui h5 and take G^k_ij(tau) from the input MF
                                            # if "coqui": read G^k_ij(tau) from the existing "outdir/prefix.mbpt.h5"
interaction   = "eri"
outdir        = "./"
prefix        = "mbpt_downfold"
wannier_file  = "wan.h5"
screen_type   = "crpa"
permut_symm   = true
force_real    = true
div_treatment = "gygi"

[downfold_1e]
mean_field    = "mf_qe"
outdir        = "./"
prefix        = "mbpt_downfold"
wannier_file  = "wan.h5"
dc_type       = "gw"
qp_selfenergy = false
update_dc     = true
force_real    = true
