[mean_field.qe]
name     = "mf_qe"
prefix   = "pwscf"
outdir   = "qe_output_dir/OUT/"
filetype = "h5"

[interaction.thc]
name        = "eri"
mean_field  = "mf_qe"
storage     = "incore"
thresh      = 1e-6
chol_block_size = 8
distr_tol   = 0.4

[mf_downfold]
interaction   = "eri"
outdir        = "./"
prefix        = "mf_downfold"
wannier_file  = "wan.h5"
beta          = 2000
lambda        = 1200.0
iaft_prec     = "high"
screen_type   = "bare"
permut_symm   = true
force_real    = true
div_treatment = "gygi"
